# DO NOT EDIT!
# This code was auto generated by the `protoc-gen-pokete-resources-python` plugin,
# part of the pokete project, by <lxgr@protonmail.com>
from typing import TypedDict


class WeatherDict(TypedDict):
    info: str
    effected: dict[str, float]
    miss_chance_modifier: dict[str, float]
    global_miss_modifier: float
    icon: str
    cycle_weathers: list[str]
    cycle_weights: list[float]


class Weather:
    def __init__(
        self,
        info: str,
        effected: dict[str, float],
        miss_chance_modifier: dict[str, float] | None = None,
        global_miss_modifier: float = 0.0,
        icon: str = "",
        cycle_weathers: list[str] | None = None,
        cycle_weights: list[float] | None = None,
    ):
        self.info: str = info
        self.effected: dict[str, float] = effected
        self.miss_chance_modifier: dict[str, float] = miss_chance_modifier or {}
        self.global_miss_modifier: float = global_miss_modifier
        self.icon: str = icon
        self.cycle_weathers: list[str] = cycle_weathers or []
        self.cycle_weights: list[float] = cycle_weights or []

    @classmethod
    def from_dict(cls, _d: WeatherDict | None) -> "Weather | None":
        if _d is None:
            return None
        return cls(
            info=_d["info"],
            effected=_d["effected"],
            miss_chance_modifier=_d.get("miss_chance_modifier", {}),
            global_miss_modifier=_d.get("global_miss_modifier", 0.0),
            icon=_d.get("icon", ""),
            cycle_weathers=_d.get("cycle_weathers", []),
            cycle_weights=_d.get("cycle_weights", []),
        )

    @staticmethod
    def validate(_d: WeatherDict) -> bool:
        return all([
            "info" in _d and type(_d["info"]) is str,
            "effected" in _d and all(type(item) is float or type(item) is int for _, item in _d["effected"].items()),
        ])

    def to_dict(self) -> WeatherDict:
        ret: WeatherDict = {}
        
        ret["info"] = self.info
        ret["effected"] = self.effected
        ret["miss_chance_modifier"] = self.miss_chance_modifier
        ret["global_miss_modifier"] = self.global_miss_modifier
        ret["icon"] = self.icon
        ret["cycle_weathers"] = self.cycle_weathers
        ret["cycle_weights"] = self.cycle_weights

        return ret
